[build]
  command = "npm ci && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_CONFIG_FUND = "false"
  NPM_CONFIG_AUDIT = "false"

# Configurações específicas para Next.js + Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  # Forçar Node.js runtime para todas as functions
  node_bundler = "esbuild"
  
[dev]
  # Configuração para netlify dev
  framework = "next"
  targetPort = 3000