[build]
  command = "npm ci && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_CONFIG_FUND = "false"
  NPM_CONFIG_AUDIT = "false"

# Sem configuração de functions por enquanto - usar padrão Netlify
  
[dev]
  # Configuração para netlify dev
  framework = "next"
  targetPort = 3000